# SwiftLint configuration for Skryn

included:
  - Skryn/Skryn
  - Skryn/SkrynTests

excluded:
  - Skryn/Skryn.xcodeproj

# Relaxed rules for a small app
disabled_rules:
  - trailing_comma
  - todo
  - nesting

opt_in_rules:
  - empty_count
  - closure_spacing

line_length:
  warning: 140
  error: 200

type_body_length:
  warning: 750
  error: 950

file_length:
  warning: 950
  error: 1150

function_body_length:
  warning: 60
  error: 100

identifier_name:
  min_length: 1
  max_length: 60
